### ISSUE TITLE
POI search: merge near objects with same label and type

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#266] opened 2017-03-03 08:17 UTC
With Qt client code, when POI search is enabled (with Marisa), search may result many duplicates. For example for metro station that is created by many separate points.

![metro-search-duplicates-small](https://cloud.githubusercontent.com/assets/309458/23543306/e10370b2-fff1-11e6-8606-635f16c7380b.png)

I am not sure where merging should be done, there are two possible places: `LocationListModel`, `DBThread`. Model slots are called in UI thread context, some expensive computations may hit usability, but DBThread works with databases independently here...

**Comment by Framstag** [comment] 2017-03-04 20:29
There is another place? What about filling the TextIndex instead based on the node, area and way data files based on the location index itself? At least I did not see the same effect in the normal location search (though I ask myself, why it would be different)?

So: What does the location index return for the same query? And if the location index has the same problem, how could/would be solve it there? And would filling the text index based on the location thus help?

**Comment by Karry** [comment] 2017-03-05 17:23
Well, when I test "Florenc, Praha", I get results from location index (I guess). There are duplicates too. There are few `railway_subway_entrance` entries that are just a few meters around station... Such entries can be merged in result view...

**Comment by Framstag** [comment] 2017-03-05 17:39
Can you give a concrete command line call for location and text index search via the demo tools so I can take a closer look?

**Comment by Karry** [comment] 2017-03-06 10:35
```
$ wget https://osmscout.karry.cz/europe/czech-republic-11-20170301.tar
$ tar -xf czech-republic-11-20170301.tar 
$ ./Demos/LocationLookup europe-czech-republic "Florenc, Praha" | grep -B 2 highway_bus_stop
= POI (Florenc) = Praha
   * Praha/Česko
   - Node 43231264 highway_bus_stop
--
= POI (Florenc) = Praha
   * Praha/Česko
   - Node 43229708 highway_bus_stop
--
= POI (Florenc) ~ Hlavní město Praha
   * Hlavní město Praha/Praha/Česko
   - Node 43231264 highway_bus_stop
--
= POI (Florenc) ~ Hlavní město Praha
   * Hlavní město Praha/Praha/Česko
   - Node 43229708 highway_bus_stop
--
= POI (Florenc) ~ okres Hlavní město Praha
   * okres Hlavní město Praha/Hlavní město Praha/Praha/Česko
   - Node 43231264 highway_bus_stop
--
= POI (Florenc) ~ okres Hlavní město Praha
   * okres Hlavní město Praha/Hlavní město Praha/Praha/Česko
   - Node 43229708 highway_bus_stop
```

**Comment by Framstag** [comment] 2017-03-07 18:39
I can reproduce the problem. Looking further...

**Comment by Framstag** [comment] 2017-03-07 19:19
The location search first searches for an admin region containing "Praha".

It first finds: https://www.openstreetmap.org/relation/435541, but it also finds https://www.openstreetmap.org/relation/435514 and https://www.openstreetmap.org/relation/439841. For each admin region it searches for the given POI name by recursivly traversing the admin region tree down (see LocationIndex::VisitRegionLocationEntries()), and finds (besides others) two busstops.  So were get in result 3 times 2 busstops. 

Since the admin level of each region is different I assume that they contain each other (this is difficult to judge from the rendered map)? If this is the case the problem can be solved if we first sort the found admin levels (in LocationService::SearchForLocations()) by admin level (increasing) - though the admin level is not yet available in this data structure, but could be calculated based on recursion level during tree traversal. For each admin region we analyse we then first check if did not traverse a parent admin level before. In this case we (of course) do not traverse the admin level again.

**Comment by Framstag** [comment] 2017-03-07 19:21
Are there other sets of problems or can your findings always be reduced to this problem category?

**Comment by Karry** [comment] 2017-03-08 08:00
That some concrete nodes are listed three times (43229708, 43231264), it is just partial problem. But yes, it should be fixed too ;-) But both `bus_stop` nodes ( [43229708 / 293572113](http://www.openstreetmap.org/node/293572113) , [43231264 / 282546215](http://www.openstreetmap.org/node/282546215)) are just 100 meters away. When I am 3 kilometers from it, I don't care about that there are two separate nodes. It may be merged to one result line... But when I am near them, I want to know that there are to two stops, one on street "Křižíkova" and second around the corner on street "Ke Štvanici"...

**Comment by Framstag** [comment] 2017-03-08 18:45
Then the merging is something that has to be done as a postprocessing step of the actual search. Doing such postprocessing would require the referenced objects to be loaded to get their geo location.

So we would need the following additional methods and structures:
* A typedef for a set of ObjectFileRefs
* A result object that holds all resolved ObjectFilesRefs
* A method in the Database that does all the resolving of ObjectFileRefs to such result class
* A method in the location service that returns a set of ObjectFileRefs based on the location search result
* A method in the location service that filters/reduces the location search result based on:
** the current geo location 
** a min distance between the current geo location and the object to start filtering (definition of "far away")
** a max distance for merging locations with the same attributes ("too close for separating if far away")
** A comparator interface that defines the "equals" condition for two search result entries ("same region, same name, same type)

That does not sound like a "hack together in a few minutes". But it would likely be a useful addition :-)

Since we now have one bug and one feature request, we should though split this issue :-)

**Comment by Karry** [comment] 2017-03-09 07:14
You are right. I created new issue for location index duplicity problem: https://github.com/Framstag/libosmscout/issues/269 I suggest to keep this one for additional merging of near different objects...

**Closed** 2017-10-22 21:29 UTC
Labels: enhancement, help wanted, location
