### ISSUE TITLE
Address for POI

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#192] opened 2017-01-02 19:40 UTC
It would be great if we could preserve the address of POI. It seems that libosmscout strips relationship between POI and the building it is in. For example, search in Tallinn:

 http://www.openstreetmap.org/search?query=subway%2C%20tallinn#map=19/59.43840/24.75866

would list Subway with the addresses. I am not sure the same info is kept in libosmscout. As far as I could see in LocationIndexGenerator, we either have POI or address in childRegion. Or am I wrong?

**Comment by Framstag** [comment] 2017-01-03 12:09
At first glance, the OSM objects itself do not have an address assigned. See for example https://www.openstreetmap.org/node/3816806733. So I assume that nominatim is extracting the address from the surrounding building. Which would be https://www.openstreetmap.org/relation/3246799#map=17/59.42158/24.79399. This is something that libosmscout currently does not do, but would be a valid extension. This is however tricky since there are many buildings, which you cannot assume to hold in memory completely. So we have to find a batch-like solution that is fast and can handle a huge number of data. Would be interesting to know how nominatim solves this (though is may be that it just does a query into the PostgisSQL database for nodes which do not have an address but should be addressable).

Btw., in the overview the subway is listed as Subway, 5,... . Where is the "5" coming from? I wounder if there is another data source for this?

**Comment by rinigus** [comment] 2017-01-03 12:37
Number 5 comes from the building address, as far as I remember from looking up this example yesterday. I suspect that the reverse geocoding is done there and that is not 'cheap' operation...

**Comment by rinigus** [comment] 2017-01-03 17:53
Indeed, that node does not seem to have any relationship to the building in OSM. But maybe we could just use the same approach as used for assigning  POI to area extended to buildinds (addresses) while importing

**Comment by Framstag** [comment] 2017-01-03 18:57
This is in principle a "coord in area" test. The problem is, there are many buildings. You cannot assume to hold all buildings in memory (will not work for france or germany), so one has to find another way. The question is, how many objects are there that should have an address, do not have an address but whose address can be potentially resolved by the surrounding building? If this number is rather small one can make a simple lookup against the AreaAreaIndex as postprocessing.

**Comment by rinigus** [comment] 2017-05-07 12:32
I looked into the number of buildings and, agreed, its a major undertaking which is probably impractical during import. I would suggest to close this issue as impractical.

**Comment by Framstag** [comment] 2017-05-07 16:53
I agree. Thus closing.

**Closed by Framstag** 2017-05-07 16:53 UTC
Labels: database, enhancement, help wanted, importer, location
