### ISSUE TITLE
BasemapImport giving up

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#937] opened 2020-10-09 08:23 UTC
I tried to update the basemap using the following command : 

```BasemapImport --destinationDirectory . --coastlines coastlines-split-4326/lines.shp```

But the command finished with the following output : 

```
   WW Detected intersection 18446744073709411179 <> 18446744073709411208
   WW Detected intersection 18446744073709483595 <> 18446744073708995787
   Filter encapsulated coastlines
   Calculate covered tiles
   Initial 678307 coastline(s) transformed to 7423 coastline(s)
   Marking cells containing coastlines
   Handle coastlines partially in a cell
   too many steps, give up! (2)          <------- I added the (2) because there are two occurrences for this log 
   WW Can't walk around cell (357,784) boundary!
   Handle area coastline completely in a cell
   Calculate coast cell environment
   Filling water
   Filling water around islands
   Filling land
   Writing index for level 10, 1048576 cells, 35052 entries, 3 bytes/entry, 8.1 MiB
   Found 678315 coastline(s)
```

The (2) log came from ``` WaterIndexProcessor.cpp ``` : 

```
      else {
        WalkPath(groundTile,
                 stateMap,
                 cellBoundaries,
                 pathStart,
                 pathEnd,
                 coastline);
      }

      step++;
      if (step>1000) { // last use
        // put breakpoint here if computation stucks in this loop :-/
        std::cout << "   too many steps, give up! (2)" << std::endl;
        return false;
      }
```

I tried to bump up the 1000 constant without success and event remove the test but the process never terminate in this case.

**Comment by vyskocil** [comment] 2020-10-09 08:26
The resulting basemap has a big hole in the whole Eurasia continent at higher zoom level : 

![IMG_9238](https://user-images.githubusercontent.com/452704/95560484-a2663700-0a19-11eb-8252-28563789081d.PNG)

But at lower zoom it is ok : 

![IMG_9239](https://user-images.githubusercontent.com/452704/95560535-b9a52480-0a19-11eb-84b5-bf6a0cacba90.PNG)

And there seems that there are no other holes in the other continents

**Comment by Karry** [comment] 2020-10-10 08:01
Hi. This problem occurs when two coastline areas share the same point if I remember it correctly. Simple walk algorithm may stuck with it. I will try to look how to workaround it this weekend.

**Comment by Framstag** [comment] 2020-10-10 08:03
I rechecked the BasemapImport with an old coastline shape file and also checked with the current shapefile from https://osmdata.openstreetmap.de/data/coastlines.html (WGS84) - in both cases the import run through. I do see above warning with the old file, too.

However I can reproduce the defect with europe with the new, current file, but not with my old one. So either this is a bug in the shape file or a bug in the water index generator that is triggered by the new shape file.

**Comment by Karry** [comment] 2020-10-11 09:42
Hi. 

There are two issues:

 - one in processing code that ends with infinite loop and that `too many steps, give up!` message. It happens when coastline node is exactly on the tile edge. Processing code then detects two intersections with the tile on the same place. With DEBUG_COASTLINE macro it prints: 

```
 - cell 357,784
    cell boundaries: 47.81250 -54.49219; 47.81250 -54.14062; 47.98828 -54.49219; 47.98828 -54.14062
    intersections:
      47,84428 N 54,14062 W (27, in, 39, 0.00018)
      47,81755 N 54,14062 W (4896, out, 2, 0.00077)
      47,81250 N 54,19444 W (4896, in, 5, 0.00001)
      47,81250 N 54,19444 W (4896, in, 0, 0.00000)
      47,81250 N 54,20566 W (27, out, 49, 0.00000)
```
On the map, it looks like this:

![Screenshot_20201011_110451](https://user-images.githubusercontent.com/309458/95674610-9ca35980-0bb1-11eb-9f98-6210f82316f5.png)

And problematic island is here: https://www.openstreetmap.org/way/129583958#map=11/47.7169/-54.2443
Here should be the fix for this issue: https://github.com/Framstag/libosmscout/pull/940

But it is far away from Euroasia that is flooded by water. This is second problem

 - second problem with flooded Euroasia is problem in the data. There are multiple isles in Siberia that are tagged with natural=coastline 

![Screenshot_20201011_112503](https://user-images.githubusercontent.com/309458/95675018-6f0bdf80-0bb4-11eb-85ca-999705186e81.png)

Here link to coastline checker from Geofabric: http://tools.geofabrik.de/osmi/?view=coastline&lon=87.05938&lat=73.99898&zoom=10&opacity=0.80&overlays=coastline,coastline_error_lines,line_not_a_ring,line_overlap,line_invalid,line_direction,questionable,coastline_error_points,unconnected,intersections,not_a_ring,double_node,tagged_node

It seems like leftover from some import, there are duplicate islets properly tagged on riverbank. So I was removed the wrong one: https://www.openstreetmap.org/changeset/92296319#map=10/74.0388/87.3289 Fix in coastlines shapefiles should land soon...

**Comment by Framstag** [comment] 2020-10-11 13:30
@vyskocil: Patches have been merged. Please test again and close if fixed.

**Closed** 2020-10-12 20:30 UTC
Labels: bug, help wanted

**Comment by vyskocil** [comment] 2020-10-12 20:34
I updated to the latest code, downloaded the coastlines file dated 2020-10-12T06:38 and now it is ok, thank you !
