### ISSUE TITLE
lands flooded by seas

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#224] opened 2017-01-28 14:32 UTC
At low zoom levels the land/sea calculation code is not working in some places, some land and sea mixed tiles are seen as only sea tiles, like here for example : 

![screen shot 2017-01-28 at 15 17 53](https://cloud.githubusercontent.com/assets/452704/22397277/6af39b6a-e56e-11e6-9fe9-562b6475110c.png)

The map data is from geofabrik south america extract, the map image is drawn using the Qt backend with OSMScout StyleEditor.

**Comment by Framstag** [comment] 2017-01-28 17:44
I'll take a look (and hope that the import does not take too long).

**Comment by Framstag** [comment] 2017-01-28 20:18
Short note: I can reproduce the problem in principle. For my concrete import though the problematic areas seem to be different, though. It look like at least some location could be the result of mapping errors. I'll take a look. Example: Flooding around https://www.openstreetmap.org/relation/6890616

**Comment by Framstag** [comment] 2017-01-28 22:11
OK, one error (not visible in your picture) is:
https://www.openstreetmap.org/way/468731107

this is a obvious mapping error. One could try to filter coastlines by bounding box, dropping coastlines that are too small, to avoid such errors, but I'm unsure, if this will not result in other problems (possibly there are valid cases?)?

**Comment by vyskocil** [comment] 2017-01-28 22:30
Why someone would imagine thus things... ! I already saw the same error (using coastlines to map some lakes or water surface...) in some other places... Yes this is a obvious error but I don't think all the other flooded areas are the results of the same mistake.
I think the bounding box test would not work because small islands are mapped using coastlines and they would be dropped with such a filter...

**Comment by Framstag** [comment] 2017-01-28 22:39
Another case is https://www.openstreetmap.org/way/24512937, which seams to be a coastline for an island, where the lake the island is in does not seem to have a coastline: https://www.openstreetmap.org/relation/3000330 - or the algorithm does not correctly handle this. For this I would have to take a deeper look.

**Comment by Framstag** [comment] 2017-01-28 23:00
I'm still struggling to get the other problems debugged.

The error top left could be produced by https://www.openstreetmap.org/way/12441173 The region is tricky anyway because it is the connection to north-america, possibly missing or incomplete coastline do irritate the algorithm.

If you activate the line
{code}
[TYPE _tile_coastline] WAY {color: #ff0000; displayWidth: 0.1mm;}
{code}

in the style sheet, you see that there is no coastline in that area.

**Comment by aquiles2k** [comment] 2017-01-30 13:03
Just noticed today that the latest bayern import has some strange extended areas. Might have something to do with this?
![byernimport_v11](https://cloud.githubusercontent.com/assets/6095108/22424004/ce51b2c8-e6f4-11e6-904b-b8efb3821c21.png)

**Comment by vyskocil** [comment] 2017-01-31 13:47
the natural=coastline used in lands errors that were cited above were all fixed, it seems that there is a active community fixing these errors and OSM newbie mappers introducing them from time to time...

**Comment by Framstag** [comment] 2017-02-01 06:36
I have now pushed some changes: Improved debugging, some code refactoring (and some more inline documentation). I also reworked parts of the water/land detection (pushed earlier). Now also small area costlines (normally islands) are filtered out. This seems to have reduced effect caused by rounding errors. The overall appearance is now better, though errors still exists.

Regarding "Bayern". I can reproduce the problem but have not analysed it yet. Note that there were also some changes from geofabrik in the exports. Relations are now guaranteed to be complete, thus such effects are not unexpected.

**Comment by aquiles2k** [comment] 2017-02-18 17:48
FYI: Regarding "Bayern" (its in the germany map from geofabrik too). i just  found out that this strange appendix is due to some little artefacts in the map. So its the data not the lib in this case.
![map_artifact](https://cloud.githubusercontent.com/assets/6095108/23095490/bcf79e64-f60a-11e6-8a8e-955be5a54eea.jpg)

**Comment by Framstag** [comment] 2017-03-19 18:47
I close the issue now.  I looks like:
* I fixed some cases
* Other cases are because of broken data
* Other cases are because of spurious data outside the expected area clipping region

If we again get problems because of error sin the water index generation itself, we can still make a new issue from it.

**Closed by Framstag** 2017-03-19 18:47 UTC
Labels: bug, help wanted, importer
