### ISSUE TITLE
Case study: Failure to find target for routing 

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#153] opened 2016-11-06 21:12 UTC
Hi! Here is one more case from @otsaloma testing. When calculating a route in Helsinki, using Mapzen Metro extract https://mapzen.com/data/metro-extracts/metro/helsinki_finland/ , routing fails due to inability to find target at https://github.com/Framstag/libosmscout/blob/master/libosmscout/src/osmscout/RoutingService.cpp#L1084 (GetTargetNodes returns false). To reproduce:

```
Demos/Routing --car ../../map/helsinki_finland 60.1674 24.9426 60.2184 24.8117
```

results in `There was an error while calculating the route!`

**Comment by Framstag** [comment] 2016-11-09 22:50
The router currentl is not able to handle areas as start or target node (it is simple to add, but just not implemented). See GetStartNodes() and GetTargetNodes(). The method GetClosestRoutableNode() though does return areas.

I have now changed GetClosestRoutableNode() to ignore areas as long as the router is not enhanced.

The route though still does not work. IMHO the problem is, that https://www.openstreetmap.org/way/35780807 is not allowed to be used for motor cars. So the target is simply not reachable by car.

Does this help you?

2546679

**Comment by rinigus** [comment] 2016-11-10 21:50
Thank you! I was trying few tests tonight, but there is a bit more to be tested still. Give me 1-2 days and I will get back to you regarding this issue.

**Comment by rinigus** [comment] 2016-11-11 21:44
While testing the newest version, after your fix, I stumbled on a similar route request that ended up with (what seems) to be an infinite loop. That happens if I use Finland http://download.geofabrik.de/europe/finland-latest.osm.pbf map, not just Helsinki:

Demos/Routing --car ../../map/finland 60.168270 24.945628 60.218473 24.812518

It looks like this destination point is rather nasty one with, in addition to libosmscout, Mapzen, and few others failing to provide route. I have seen only OSRM being able to calculate route there:

[http://www.openstreetmap.org/directions?engine=osrm_car&route=60.2025%2C24.8658%3B60.2190%2C24.8108](http://www.openstreetmap.org/directions?engine=osrm_car&route=60.2025%2C24.8658%3B60.2190%2C24.8108)

(see at URL how it fails with Mapzen). However, in case of Mapzen, no infinite loop was observed.

**Comment by otsaloma** [comment] 2016-11-11 23:13
The north side of the Sello Shopping Center is a bus terminal and is at least in part forbidden for cars, so at least a part of those `motorcar=no` are correct. Sello has underground parking accessible via streets on the south and west sides.

I understand this can be difficult for routing and I wouldn't expect to be guided to the correct parking ramp, but I would expect to be routed somewhere in the vicinity, where one could follow signs for the rest of the way. How exactly should you find the closest routable street node, I have no suggestion to offer.

This problem can come up when people search for place, e.g. in this case "Sello, Espoo", or if they are in the shopping center and search for a route from the current GPS position to somewhere else. Both of these should be fairly common.

**Comment by Framstag** [comment] 2016-11-12 15:08
@otsaloma: I assume you comment is in response to the first problem? The demo application gets two coordinates, one for the start, one for the target location. It then looks for the closest routable nodes. So if you are driving by car and you point it to a shopping center it looks for the next way that can be used by a car - though it currently looks only for the way type, it may select ways that are in principle routable but the concrete instance though is not. That is something I can fix but changing the API of the GetClosestRoutableNode() and passt the RoutingProfile, too (See issue #155). This way, selection of an routable way should be improved.

It still can happen though, that there is a way around the shopping center, that can be used by a car but that is in no way connected to any street or highway (in reality the situation might be more complex, but I hope you get the idea). This is something the router cannot solve (perfectly, automatically). I would expect the app to either ask the user for a better start or target point in this case or try to select one itself based on some heuristic (which could be placed into the library though again). The router though might collect some additional statistics (maximum distance from the start point) to give the application a hint where the router has failed (see issue #156).

**Comment by rinigus** [comment] 2016-11-12 16:18
It looks to me that Mapzen and MapQuest do exactly the same mistake as osmscout - select a closest routing point that is routable by type and then fail to get there since its inaccessible. As soon as I shift target to southern part of the center, all routers find the  way (very easy to test in @otsaloma's Poor Maps!). 

OSRM does not have this issue. I presume it's since it creates hierarchy of routes and selects target from that hierarchy. So, to resolve this we should probably have some similar approach, at least on the level of routing points. I guess, that's the stats you want to collect as a part of other issue.

**Comment by otsaloma** [comment] 2016-11-12 17:24
> It still can happen though, that there is a way around the shopping center, that can be used by a car but that is in no way connected to any street or highway.

My experience tells me that completely unconnected roads are such rare that they are hardly an issue to worry about. But accouting for allowed roads, not just type, sounds good. I expect it would help bicycle routing as well, assuming you don't currently account for `bicycle=no` either?

**Comment by Framstag** [comment] 2016-11-12 19:19
Issue #155 was now fixed. Both example now work (though I have not tested, how valid/good the resulting start/end nodes are).

**Comment by Framstag** [comment] 2016-11-12 19:24
Please also be aware of issue #157.

**Comment by Framstag** [comment] 2016-11-12 21:23
Issue #157 was now also fixed. Can we close the issue now :-)?

**Comment by rinigus** [comment] 2016-11-12 22:27
Just checked the original case (Sello Shopping Center) with the new version of the library. The server was able to provide the route as a response to 

http://localhost:8553/v1/route?p[0][search]=Erottaja,%20Helsinki&p[1][search]=Sello%20Shopping&gpx=1

GPX route is attached. I don't know whether its in agreement with local rules. From the look on it, osmscout brings it now to the southern part. The target coordinate was in the middle of the center, as a response for search "Sello Shopping". So, I guess, the original issue is solved (its finding the route to the request that user would have entered). 

I'll test the new version and we can always submit new issues, if needed.

[route_to_sello.zip](https://github.com/Framstag/libosmscout/files/587483/route_to_sello.zip)

**Comment by otsaloma** [comment] 2016-11-12 22:31
Looks good to me.

**Closed** 2016-11-12 22:31 UTC
Labels: bug, help wanted, routing
