### ISSUE TITLE
Import.exe on Win11 does not work on pbf files

### ISSUE THREAD

**Issue by ChapeauClaque-RPI** [Framstag/libosmscout#1576] opened 2024-05-26 19:05 UTC
Unfortunately, I cannot manage importing a pbf file on Win11. I compiled with VS2019.
Import.exe gives:
+ Dump parameter...
   Mapfile: baden-wuerttemberg-latest.osm.pbf
   typefile: ../stylesheets/map.ost
   Destination directory: baden-wuerttemberg-latest
   Steps: 1 - 27
   Router: foot+bicycle+car - 'router'
   StrictAreas: false
   ProcessingQueueSize: 20
   NumericIndexPageSize: 1024
   RawCoordBlockSize: 60000000
   RawNodeDataMemoryMaped: false
   RawWayIndexMemoryMaped: true
   RawWayDataMemoryMaped: false
   RawWayIndexCacheSize: 10000
   RawWayBlockSize: 500000
   SortObjects: true
   SortBlockSize: 40000000
   CoordDataMemoryMaped: false
   CoordIndexCacheSize: 1000000
   CoordBlockSize: 250000
   AreaDataMemoryMaped: false
   AreaDataCacheSize: 0
   AreaWayIndexMinMag: 10
   AreaWayIndexMaxMag: 15
   WayDataMemoryMaped: false
   WayDataCacheSize: 0
   AreaNodeGridMag: 14
   AreaNodeSimpleListLimit: 500
   AreaNodeTileListLimit: 100
   AreaNodeTileListCoordLimit: 1000
   AreaNodeBitmapMaxMag: 20
   AreaNodeBitmapLimit: 20
   RouteNodeBlockSize: 500000
   MaxAdminLevel: 10
   Eco: false
   TextIndexVariant: transliterate
+ Loading type config...
   Number of types: 455
   Number of node types: 211 1 byte(s)
   Number of way types: 79 1 byte(s)
   Number of area types: 263 2 byte(s)
   Parsed language(s) :
     default
   Parsed alt language(s) :
+ Step #1 - TypeDataGenerator...
   Module description: Dump *.ost information into data file
   Module provides file 'types.dat'
 - Generate types.dat...
   Number of types: 455
   => 0.003s
+ Step #2 - Preprocess...
   Module description: Initial parsing of import file(s)
   Module provides file 'bounding.dat'
   Module provides temporary file 'distribution.dat'
   Module provides temporary file 'rawcoords.dat'
   Module provides temporary file 'rawnodes.dat'
   Module provides temporary file 'rawways.dat'
   Module provides temporary file 'rawrels.dat'
   Module provides temporary file 'rawcoastline.dat'
   Module provides temporary file 'rawdatapolygon.dat'
   Module provides temporary file 'rawturnrestr.dat'
   Module provides temporary file 'rawroutemaster.dat'
   Module provides temporary file 'rawroute.dat'
   Using 20 block worker threads with queue size of 20
   !! Support for the PBF file format is not enabled!
   Waiting for block processor...
   Waiting for block processor done.
   Waiting for write processor...
   Waiting for write processor done.
 - Dump statistics...
   => 0.005s
   !! Import failed: File 'baden-wuerttemberg-latest\bounding.dat' - Cannot read size of file: Das System kann die angegebene Datei nicht finden.

How do I enable the PDF file support? I already downloaded protoc.exe and pointed the PATH variable to it (this runs) before compiling.
In another post you mentioned, that I have to link Import to protobuf but I dont know how.
Please help me, thanks.

**Comment by Framstag** [comment] 2024-05-27 17:24
protobuf not just an executable it is also a corresponding ibrary. See the Visual Studio vcpkg Build: https://github.com/Framstag/libosmscout/blob/master/.github/workflows/build_and%20test_on_vs2019.yml It uses the following vcpkg configuration: https://github.com/Framstag/libosmscout/blob/master/vcpkg_medium.json See the protobuf dependency. in this file 

Note that we had problems with using protobuf under Windows.  The vcpbg build did work fine, but execution seemed to fail. LIke the compiler options for protobuf and loibosmscout did not match well. This should be solable, since it works perfectly under Linux.

If we can be of further help, just ask.

**Comment by Framstag** [comment] 2024-05-27 17:26
The cmake  bildl file should show you , if protobuf was correctly found:

if (TARGET protobuf::libprotobuf AND EXISTS ${PROTOBUF_PROTOC_EXECUTABLE})
  message(STATUS "- protobuf:                      TRUE")
else ()
  message(STATUS "- protobuf:                      FALSE")
endif ()

**Comment by Framstag** [comment] 2024-05-30 07:30
@ChapeauClaque-RPI : Did this help you? As this is not a bug in libosmscout I would like to close the issue. Or do you have further questions?

**Comment by ChapeauClaque-RPI** [comment] 2024-05-30 07:41
Is there anyone, who has a win binary Release of the pbf importer? And yes, then please Close.

Am 30. Mai 2024 09:30:32 MESZ schrieb Tim Teulings ***@***.***>:

**Comment by Framstag** [comment] 2024-05-30 08:15
The Visual Studio build does export it build artefacts, see

https://github.com/Framstag/libosmscout/actions/runs/9212167863

I haven't tested them recently, though. Make sure that the librarys/DLLs are in the search path of the binaries.

I keep the issue open until you have tested, if the download and its contains work.

**Comment by ChapeauClaque-RPI** [comment] 2024-05-31 18:56
Great, thank you, I will check this. Pleas ignore my last message per mail, I was not logged on.

**Comment by Framstag** [comment] 2024-06-04 05:09
@ChapeauClaque-RPI : Have you already tested the prebuild binaries?

**Comment by Framstag** [comment] 2024-06-04 13:54
Imports are not linear in execution time in regard to import size. We thus recommend to generate multiple smaller imports instead of one big one. The library can join them and routing across database borders is possible.

**Comment by Framstag** [comment] 2024-06-16 06:41
@ChapeauClaque-RPI : Any news on this?

**Comment by jheaff1** [comment] 2024-06-17 14:08
I'm experiencing the same issue:

```
 Import failed: File '...................\bounding.dat' - Cannot read size of file: The system cannot find the file specified.
```

**Comment by Framstag** [comment] 2024-06-22 08:29
I'll take a look over the weekend. I'll check with current baden-wuerttemberg-latest.osm.pbf from Geofabrik.

@jheaff1 : Which *.pbf file did you use?

**Comment by Framstag** [comment] 2024-06-22 09:00
I was able to generate a database using the MinGW build. I'll check a VC build next...

**Comment by Framstag** [comment] 2024-06-22 09:32
@jheaff1 
@ChapeauClaque-RPI 

The import starts, I see no obvious problem. 

* I downloaded current binaries from the zip from https://github.com/Framstag/libosmscout/actions/runs/9623630601
* I unpacked the to c:\projects\test
* I opended a DOS shell and set current directory to c:\projects\libosmscout\maps (My current repository snapshot)
* I added the path to the test dirctory to PATH: `set PATH=c:\projects\test;%PATH%`
* (Make sure that the target directory exists)
* (make sure you use the right import by `where Import.exe`)
* Start the import: `Import.exe  --typefile ..\stylesheets\map.ost --destinationDirectory baden-wuerttemberg baden-wuerttemberg.osm.pbf`

Import starts:
```
+ Dump parameter...
   Mapfile: baden-wuerttemberg.osm.pbf
   typefile: ..\stylesheets\map.ost
   Destination directory: baden-wuerttemberg
   Steps: 1 - 27
   Router: foot+bicycle+car - 'router'
   StrictAreas: false
   ProcessingQueueSize: 16
   NumericIndexPageSize: 1024
   RawCoordBlockSize: 60000000
   RawNodeDataMemoryMaped: false
   RawWayIndexMemoryMaped: true
   RawWayDataMemoryMaped: false
   RawWayIndexCacheSize: 10000
   RawWayBlockSize: 500000
   SortObjects: true
   SortBlockSize: 40000000
   CoordDataMemoryMaped: false
   CoordIndexCacheSize: 1000000
   CoordBlockSize: 250000
   AreaDataMemoryMaped: false
   AreaDataCacheSize: 0
   AreaWayIndexMinMag: 10
   AreaWayIndexMaxMag: 15
   WayDataMemoryMaped: false
   WayDataCacheSize: 0
   AreaNodeGridMag: 14
   AreaNodeSimpleListLimit: 500
   AreaNodeTileListLimit: 100
   AreaNodeTileListCoordLimit: 1000
   AreaNodeBitmapMaxMag: 20
   AreaNodeBitmapLimit: 20
   RouteNodeBlockSize: 500000
   MaxAdminLevel: 10
   Eco: false
   TextIndexVariant: transliterate
+ Loading type config...
   Number of types: 455
   Number of node types: 211 1 byte(s)
   Number of way types: 79 1 byte(s)
   Number of area types: 263 2 byte(s)
   Parsed language(s) :
     default
   Parsed alt language(s) :
+ Step #1 - TypeDataGenerator...
   Module description: Dump *.ost information into data file
   Module provides file 'types.dat'
 - Generate types.dat...
   Number of types: 455
   => 0.003s
+ Step #2 - Preprocess...
   Module description: Initial parsing of import file(s)
   Module provides file 'bounding.dat'
   Module provides temporary file 'distribution.dat'
   Module provides temporary file 'rawcoords.dat'
   Module provides temporary file 'rawnodes.dat'
   Module provides temporary file 'rawways.dat'
   Module provides temporary file 'rawrels.dat'
   Module provides temporary file 'rawcoastline.dat'
   Module provides temporary file 'rawdatapolygon.dat'
   Module provides temporary file 'rawturnrestr.dat'
   Module provides temporary file 'rawroutemaster.dat'
   Module provides temporary file 'rawroute.dat'
   Using 16 block worker threads with queue size of 16
 - Parsing *.osm.pbf file 'baden-wuerttemberg.osm.pbf'...
   Feature 'OsmSchema-V0.6'
   Feature 'DenseNodes'
   Start reading nodes
   % 2.43 (14214353/584653554)
   % 4.60 (26899135/584653554)
   % 6.21 (36304321/584653554)
   % 7.93 (46349098/584653554)
   % 10.09 (58996740/584653554)
   % 12.26 (71695891/584653554)
   % 14.17 (82817009/584653554)
   % 15.86 (92697336/584653554)
   % 17.41 (101769508/584653554)
   % 18.93 (110672516/584653554)
   % 20.23 (118285697/584653554)
   % 20.70 (121020867/584653554)
   % 21.17 (123772683/584653554)
   % 21.66 (126627015/584653554)
   % 22.13 (129363138/584653554)
   % 22.61 (132179645/584653554)
   % 23.09 (134968870/584653554)
   % 23.32 (136326542/584653554)
   % 23.43 (136960792/584653554)
   % 23.89 (139677239/584653554)
   % 24.36 (142442473/584653554)
   % 24.81 (145025688/584653554)
   % 25.27 (147758038/584653554)
   % 25.74 (150518501/584653554)
   % 26.20 (153204176/584653554)
   % 26.67 (155951725/584653554)
   % 27.11 (158521536/584653554)
   % 27.56 (161106266/584653554)
   % 28.01 (163769439/584653554)
   % 28.47 (166452866/584653554)
   % 28.90 (168976182/584653554)
   % 29.33 (171451104/584653554)
   % 29.74 (173885540/584653554)
   % 30.19 (176514147/584653554)
   % 30.75 (179753332/584653554)
   % 31.87 (186353486/584653554)
   % 32.93 (192503170/584653554)
   % 33.66 (196817773/584653554)
   % 34.07 (199207854/584653554)
   % 34.18 (199853787/584653554)
   % 34.30 (200525636/584653554)
   % 34.43 (201282470/584653554)
   % 34.63 (202479263/584653554)
   % 34.95 (204343970/584653554)
   % 35.07 (205018529/584653554)
   % 35.99 (210414760/584653554)
   % 36.64 (214212049/584653554)
   % 37.14 (217124198/584653554)
   % 37.47 (219082510/584653554)
   % 37.55 (219525160/584653554)
```

The same for a local Visual Studio 2022 based build...

I assume a setup roblem. You possibly make use of libraries from somewhere else?

**Comment by jheaff1** [comment] 2024-06-24 06:56
Hi @Framstag, thank you very much for looking into this in your spare time, much appreciated!

I downloaded the windows binaries from the github actions run and it worked fine, so the issue must be to do with how i am building libosmscout. I'm using meson and Qt6, I wonder if that has an impact. I'll investigate

**Comment by Framstag** [comment] 2024-07-08 18:57
Hi @jheaff1 : I'm closing the issue...

**Closed by Framstag** 2024-07-08 18:57 UTC
Labels: importer, build
