### ISSUE TITLE
I can not file marisa.h file 

### ISSUE THREAD

**Issue by MuhammadHarisRafique** [Framstag/libosmscout#461] opened 2017-08-26 08:13 UTC

**Comment by MuhammadHarisRafique** [comment] 2017-08-26 08:14
And how i am running your library on ios 
display map

**Comment by vyskocil** [comment] 2017-08-26 09:55
[Marisa](http://s-yata.github.io/marisa-trie/docs/readme.en.html) is a optional dependency. You might install it to enable full text search in libosmscout bases. 
To have a demo how to display a map on iOS look at the OSMScoutOSX XCode project in the Apple sub directory.

**Comment by Framstag** [comment] 2017-08-26 17:20
Which build system are you using under Mac OS X? cmake? autotools? It looks like the marisa detection is somehow broken. I though need more information to fix this.

**Comment by MuhammadHarisRafique** [comment] 2017-08-29 09:16
Xcode 7.3



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=harismath@gmail.com&idSignature=22>

**Comment by MuhammadHarisRafique** [comment] 2017-08-29 09:17
sierra
10.12.6



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=harismath@gmail.com&idSignature=22>

**Comment by MuhammadHarisRafique** [comment] 2017-08-29 09:19
i run mac OSMScoutOSX XCode project but when i build this receving merisa.h
file not found error.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=harismath@gmail.com&idSignature=22>

**Comment by Framstag** [comment] 2017-08-29 18:03
Please subscribe to the mailing list (or read the archive), we recently have helped another user through a few obstacles before he had a working OS X build. See "Compiling libosmscout for iPhone" thread.

There seems to be a problem with miss-detected marisa detection in the cmake based build. Do you build the library using cmake? have you read http://libosmscout.sourceforge.net/documentation/source/ ?

You first need to build the library before you can build the XCode demo project itself. Did you do so?

Btw., I find it unfair to compare a small (in regard to the community) and very specialized project with two projects with >100 contributors. We are no commercial project, things are done in free time. Documentation is one of the first things to drop and exchanged with IMHO good support on the mailing list (an dthe issue tracker). You can help us by giving a detailed description of your build steps and making a good issue report in exchange, wait for the fix to get applied and then for example supply the documentation fragments you found missing. Contributor+1 :-) Win-Win

**Comment by Framstag** [comment] 2017-08-29 21:16
As stated on the list, too. I cannot reproduce this using cmake and OS X. Marisa not being available is correctly detected by the cmake build and the build in turn works.

It may though that the demo project itself still breaks. So I need more details. Does the cmake build work? If not, can you attach the output of the detection phase of cmake? Where exactly does the compile error occur?

**Comment by vyskocil** [comment] 2017-08-29 21:28
I understand what happen, the included XCode project in the Apple subdir build unconditionally TextSearchIndex.cpp from libosmscout ! This seems not be the case when building with CMake.
If you still want to compile the included XCode project without marisa you have to remove from the build target, see Target Membership  here: 

<img width="1677" alt="screen shot 2017-08-29 at 23 21 29" src="https://user-images.githubusercontent.com/452704/29845018-99ba818e-8d11-11e7-8680-604c5dcedf52.png">

**Comment by Framstag** [comment] 2017-08-31 18:42
OK. So the issue would be solved with some README entry or corresponding hint as part of the build documentation?

**Comment by MuhammadHarisRafique** [comment] 2017-09-01 06:24
OK thanks




<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=harismath@gmail.com&idSignature=22>

**Comment by Framstag** [comment] 2017-09-01 18:58
Fixed by adding a hint to the build documentation. Closing thus.

**Closed by Framstag** 2017-09-01 18:58 UTC
Labels: bug, build, help wanted
