### ISSUE TITLE
CMake build Failed when Marisa is not on Standard Path

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#588] opened 2018-03-29 07:07 UTC
if(MARISA_FOUND)
    target_include_directories(OSMScout2 PRIVATE ${MARISA_INCLUDE_DIRS})
    target_link_libraries(OSMScout2 ${MARISA_LIBRARIES})
endif()

is missing in StyleEditor/CMakeLists.txt
and OSMScout2/CMakeLists.txt

**Comment by Framstag** [comment] 2018-03-29 12:13
Thanks for the hint,  I'll take a look.

**Comment by vyskocil** [comment] 2018-03-31 12:26
MARISA detection is still broken for iOS target, adding the following on cmake  command line used to work but not anymore 

> -DMARISA_INCLUDE_DIRS=~/Dev/marisa/lib

Now I have to add 

set(MARISA_FOUND 1) in CMakeLists.txt for OSMScout

**Comment by Framstag** [comment] 2018-04-01 06:52
The initial problem from @DerKleinePunk is IMHO a transirtive dependency problem. I did some changes to the cmake builds (using more 'target' functionality) that might have fixed that anyway. So I'll check next, if the above can be removed again.

@vyskocil Your problem is a library detection problem. The current detection code in FindMarisa.cmake is rather simple. I'll take a look at the detection files later on, too, since I would also like to have detection code that defines a target, too, since this makes since much simpler in the cmake code. It might make sense to make a separate issue for this.

**Comment by Framstag** [comment] 2018-04-01 18:45
@vyskocil: I assume you are building under OSX using cmake. Marisa is installed via brew? If yes, I should be able to reproduce the problem.

**Comment by Framstag** [comment] 2018-04-02 18:51
I now build marisa manually under Mac OS X, since there was no brew formula for it. make install does install it to /usr/local (.../include and .../lib). Cmake found it automatically, since /usr/local is a place automatically search by FindMarisa.cmake.

It also works, if I call cmake with MARISA_ROOT=/usr/local cmake <further parameter> (you could also use MARISA_HOME). In this case it expects the header in $MARISA_ROOT/include and the library in lib. This works, too. Builds seems to succeed.

Details can be found in FindMarisa.cmake.

It also works now without above changes now (after I added marisa to the public includes of osmscout library). I'll thus will remove them again.

**Comment by vyskocil** [comment] 2018-04-03 09:23
It was already working for me for Mac OSX target but not for the iOS one when osmscout is cross built on Mac. Hopefully I have marisa also build iOS in a directory and then I tried to use MARISA_ROOT when doing cmake but at the end I still have this warning :  
```CMake Warning:
  Manually-specified variables were not used by the project:

    MARISA_ROOT
```

**Comment by Framstag** [comment] 2018-04-03 18:38
@vyskocil: I'm a little bit lost then, too. I'm surely not an expert in this but only interpreted the FindMarisa.cmake file. However, is cmake in your case making a native build under iOS or is cmake doing a cross-compliation build (HOST != TARGET)? See (rather old documentation) under https://cmake.org/Wiki/CMake_Cross_Compiling It could be possible that in this case, cmake behaves differently.

**Comment by DerKleinePunk** [comment] 2018-04-04 05:45
@vyskocil i'm realy bad with english but i try.
I compiling with Debian to Rasberry do this in need the "root" from PI for libs i think it is on IOS the same.
To Say CMake where the "new Lips" found you have to set the new root

SET(RPIROOT /home/punky/x-tools/rpiroot)
SET(CMAKE_SYSROOT ${RPIROOT})

SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

https://bitbucket.org/numberfive/sdl2guitests/overview
Toolchain-RaspberryPi2.cmake

cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-RaspberryPi2.cmake -DTARGET=PI

I hope it helps

**Comment by Framstag** [comment] 2020-09-21 16:57
@OgreTransporter Since you have now proven cmake mastery ;-) Any idea on this?

**Comment by OgreTransporter** [comment] 2020-09-25 14:32
> It was already working for me for Mac OSX target but not for the iOS one when osmscout is cross built on Mac. Hopefully I have marisa also build iOS in a directory and then I tried to use MARISA_ROOT when doing cmake but at the end I still have this warning :
>   Manually-specified variables were not used by the project:
> 
>     MARISA_ROOT

Yes, it's correct! `MARISA_ROOT` is accepted as system environment variable, not as CMake parameter!

I added more hints to FindMarisa in the https://github.com/Framstag/libosmscout/pull/917/commits/a5912fd4c695efb919dcc0fb9c21fc5f0d90e609 commit. Now 'MARISA_ROOT' and 'MARISA_HOME' should also work as CMake parameters.

**Comment by OgreTransporter** [comment] 2020-11-03 08:08
I think this issue is solved.

1. I have fixed the error in FindMarisa when switching the CMake scripts
2. It is always possible (even before the changeover) to specify the directories directly if necessary: `-D MARISA_INCLUDE_DIRS:PATH=D:\marisa\install\include -D MARISA_LIBRARIES:FILEPATH=debug;D:\marisa\install\lib\libmarisad.lib;optimized;D:\marisa\install\lib\libmarisa.lib`

**Comment by Framstag** [comment] 2020-11-08 10:50
I follow the suggestion of @OgreTransporter and close the issue.

**Closed by Framstag** 2020-11-08 10:50 UTC
Labels: bug, build
