### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#1090] opened 2021-05-18 06:59 UTC
I updated the code to the latest, compiled all the stuff then imported the latest france.osm.pbf from geofabrik using the usual command line : 

``Import --destinationDirectory . --bounding-polygon ../france.poly ../france.osm.pbf ../france.hgt.osm.pbf  > import.log 2>&1 &``

Then when I tried the rendering I could see some weird polygons all over the map like in this screenshot using StyleEditor : 

<img width="720" alt="Screenshot 2021-05-18 at 08 49 36" src="https://user-images.githubusercontent.com/452704/118606007-2e61ed80-b7b7-11eb-8614-5dc90dc968ee.png">

I could see the same issues with my iOS app.

**Comment by Karry** [comment] 2021-05-18 11:37
It is usually caused by usage "natural=coastline" somewhere in the midland... This tag should be used just on land and sea border. Water index code using that information for decide where is sea and where land. It is sensitive and doesn't filter wrong usage of this tag (it would be great to implement it).

I found one misuse in Germany: https://overpass-turbo.eu/s/17tJ but none in Frame (yet). Overpass api is not the best tool for such big areas.

**Comment by Karry** [comment] 2021-05-18 11:47
I fixed this concrete case in Germany: https://www.openstreetmap.org/changeset/104888666

**Comment by Karry** [comment] 2021-05-18 12:14
Can you upload `import.log` please?

**Comment by vyskocil** [comment] 2021-05-18 12:16
Here is the import.log file : 
[import.log.zip](https://github.com/Framstag/libosmscout/files/6501148/import.log.zip)

**Comment by vyskocil** [comment] 2021-05-18 12:19
Unfortunately I deleted the old france.osm.pbf file that was imported before without this issue... It was at least 6 month old.

**Comment by Karry** [comment] 2021-05-19 06:47
I tried to import France from today's Geofabric extract ant it failed at the beginning with `!! Cannot decode zlib compressed blob data!` message!

**Comment by vyskocil** [comment] 2021-05-19 12:37
I also downloaded today's Geofabrik france extract (https://download.geofabrik.de/europe/france-latest.osm.pbf)  and I could start the import without zlib issue on MacOS

**Comment by Karry** [comment] 2021-05-20 09:11
Exactly, it seems that file was malformed yesterday. Even coastline / land index seems to be correct now. We can track issue for better resilient for coastline errors, but it is not priority for me now.

**Comment by vyskocil** [comment] 2021-05-29 15:40
Today I checked that the French coastline seems to be ok using : [OSM Inspector](http://tools.geofabrik.de/osmi/?view=coastline&lon=1.19385&lat=49.17727&zoom=8&overlays=coastline,coastline_error_lines,line_not_a_ring,line_overlap,line_invalid,line_direction,questionable,coastline_error_points,unconnected,intersections,not_a_ring,double_node,tagged_node) then I imported the latest geofabrik dataset and could see that the issue is gone !

**Comment by Framstag** [comment] 2021-08-23 16:40
@vyskocil Is this still a problem?

**Comment by vyskocil** [comment] 2021-08-23 17:32
Since then I tried several times to import France.osm.pbf from geofabrik and saw the issue, I try again and tell you if something changed by I fear the issue is in the import code as I looked at the online coastline checker and it was ok…

**Comment by vyskocil** [comment] 2021-08-23 20:37
Here is the coastline checker : http://tools.geofabrik.de/osmi/?view=coastline&lon=1.19385&lat=49.17727&zoom=8&overlays=coastline,coastline_error_lines,line_not_a_ring,line_overlap,line_invalid,line_direction,questionable,coastline_error_points,unconnected,intersections,not_a_ring,double_node,tagged_node

**Comment by vyskocil** [comment] 2021-08-24 08:40
I just imported the latest france.osm.pbf from GeoFabrik and the issue is still there : 

<img width="484" alt="Screenshot 2021-08-24 at 10 38 42" src="https://user-images.githubusercontent.com/452704/130585443-2f888630-a526-432e-88fc-c69d8aa80a23.png">

**Comment by vyskocil** [comment] 2021-08-28 09:14
Hello @Framstag and @Karry ! How could I help to help moving forward on this issue ?

**Comment by Framstag** [comment] 2021-08-28 10:26
This part of the import is IMHO the trickiest part of the import. Based on the coastline detection, we divide the import area in a set of rectangular areas. Each area can either contain a coastline or is a water or land tile. Water and land tiles are defined by a filing algorithm that fills based on the coastline. It looks that something is broken here. In the past, the problem were AFAIK corner cases because of rounding errors or geometric situations.

The original code is by me, but @Karry did a number of enhancements for these corner cases. He also did the last analysis in case of problems.

How you can help:
* Find an "as small as possible" import that reproduces the problem. This will reduce time for import in case we need a fix in the code
* Activate     [TYPE _tile_coastline] WAY {color: #ff0000; displayWidth: 0.1mm;} in the style sheet to check for problems in the coastline
* (Untested). Disable the FillXXX methods in GEnWaterIndex.cpp. This should leave tiles of type "coastline" and "unknown". These can be colour using the style options in the style sheet. This should also be useful for visual debugging (since imports take a while, it is helpful to have a small as possible import for this).

    [TYPE _tile_sea] AREA {color: @waterColor;}
    [TYPE _tile_coast] AREA {color: /*@coastColor;*/@waterColor;}
    [TYPE _tile_land] AREA {color: @landColor;}
    [TYPE _tile_unknown] AREA {color: @unknownColor;}

In the end, this should help identify why and where libosmscout is filling land areas in error. Because of the filling algorithm, the source of the erroneous fill is not easy to detect. 

If the above helps, we can add an explicit import option for this (=> waterDebugging or similar)

@Karry : Sounds good? Further ideas?

**Comment by Karry** [comment] 2021-08-28 21:17
Hi. I verify my recent [France import from 16.8.2021](http://osmscout.karry.cz/europe/france-22-20210816-0244/) and seems to be fine. I import it [today (28.8.2021)](http://osmscout.karry.cz/europe/france-22-20210828-2218/) and looks good too. @vyskocil, do you specify `--bounding-polygon` argument? It should help the algorithm find the land and sea boundaries.

**Comment by vyskocil** [comment] 2021-08-29 07:29
@Karry yes I use ```--bounding-polygon france.poly``` but I didn't updated this file for years and just verified that it is not the same on the geofabrik site, I'm trying an import with the updated file...

**Comment by vyskocil** [comment] 2021-08-29 11:52
@Karry the issue was indeed with the old france.poly file that was not matching recent france.osm.pbf map extracts, this should have risen some bad corner cases... I think we should close the issue ?

**Comment by Framstag** [comment] 2021-08-29 16:12
Yes. Is there something we can do, so that somebody else will not have the problem? Sounds like an addition to the documentation?

**Comment by Karry** [comment] 2021-08-31 06:23
Good point. I documented common coastline troubleshooting to Import tutorial: https://github.com/Framstag/libosmscout/pull/1118

**Comment by Framstag** [comment] 2021-09-20 17:25
I assume we can close the issue?

**Closed** 2021-10-11 11:00 UTC
