### ISSUE TITLE
Import pbf file on MacBook M1 Pro

### ISSUE THREAD

**Issue by hoangbossemo** [Framstag/libosmscout#1207] opened 2022-01-24 02:27 UTC
I'm trying to import pbf file on my MacBook M1 Pro, but I got an error when running the import command. Anyone get the same error like this and how to resolve? Thank you.
<img width="1137" alt="Screen Shot 2022-01-24 at 09 21 35" src="https://user-images.githubusercontent.com/685466/150712184-9a1fa65f-5dbd-4163-a46f-b7467abfd368.png">

**Comment by hoangbossemo** [comment] 2022-01-24 03:42
I tried with arch x86_64 and got Bad CPU type in executable erro
<img width="1265" alt="Screen Shot 2022-01-24 at 10 40 38" src="https://user-images.githubusercontent.com/685466/150718529-199173d4-7ffe-4a30-965c-3f4079a36cca.png">
r

**Comment by Framstag** [comment] 2022-01-24 06:43
Hello,

I do not have an Apple M1 (only an Intel x64 based one), so I cannot directly help on this but can give more general advices.

Regarding building I recomment to follow the flow as used by the (cmake based) GitHub Action for OS X builds:

https://github.com/Framstag/libosmscout/blob/master/.github/workflows/build_and%20test_on_osx.yml

From this quickly searched article (https://discourse.cmake.org/t/how-to-determine-which-architectures-are-available-apple-m1/2401) it sounds like arm64 should be the native build architecture for the M1. Please make sure that this is correct (you could follow the hint to build universal binaries but  haven't done this before so I'm not sure if the build script would work correctly for this).

Please post the output of the configuration phase of cmake.

If the importer crashes it would be interesting why. Please make sure that you have build a debug version. Check the created log to check for errors. Please also call the importer directly (the script dumps the resulting effective command line) to make sure that the script does not hide relevant information. Try to call the importer from the debugger to get the point of crash and the call stack.

We build libosmscout on multiple architectures. I'm relative sure that we do not have architecture problems in the render and routing libraries. But it is possible that nobody yet build the importer on arm64, so there might be a problem here.

If you have callstack, location of crash, final outputs etc... please post them here, This should allow us to narrow the problem (if it is a code and not a build problem) and give you further hints for actions to locate the problem.

Hope that helps. Waiting for further information.

**Comment by Karry** [comment] 2022-01-24 11:49
Hi @hoangbossemo . If it is importer bug, it would be great to get coredump and then stacktrace with debugger. Compiler sanitizers may help to identify memory access issues. You may try to configure importer with `-DCMAKE_CXX_FLAGS=-fsanitize=address` cmake argument and reproduce the problem then.

I'm not MacOS expert, but your log prints that application was killed. It seems that it was not even started. It is possible to get some system log, similar to Linux dmesg? There may be more information what happened...

**Comment by hoangbossemo** [comment] 2022-01-25 04:11
hi @Framstag @Karry , thank for your reply.
Finally I can import successfully. I tried with .osm not .pbf extension. everything seem fine. I will test the imported data with iOS device and post in here if any issue happens. Thank you
<img width="1424" alt="Screen Shot 2022-01-25 at 11 04 24" src="https://user-images.githubusercontent.com/685466/150909435-3990e78b-823c-4bd1-addd-592ce2c84b25.png">

**Comment by Karry** [comment] 2022-01-25 07:43
Interesting. So, protobuffers are problematic. Considering that M1 is arm64, possibly unaligned memory access is the issue. Do you know what version of protobuffers do you have in build? Can you post us output of this command from build directory please?

```
cat CMakeCache.txt | grep protobuf
```

Thanks

**Comment by hoangbossemo** [comment] 2022-01-25 09:43
hi @Karry this is the result from my Mac
<img width="1212" alt="Screen Shot 2022-01-25 at 16 42 43" src="https://user-images.githubusercontent.com/685466/150952084-c6f4bb1a-12ae-4674-a4d7-6d5fb8bd3ca2.png">

**Comment by hoangbossemo** [comment] 2022-01-25 09:49
btw, when I running in iOS device I saw this:
![IMG_1267](https://user-images.githubusercontent.com/685466/150952582-e3bcda0d-1f9e-4408-8030-79be0e653cf5.PNG)
I'm using Greater London map data downloaded in here:
https://download.geofabrik.de/europe/great-britain/england/greater-london.html
When I sent the app to background
<img width="1264" alt="Screen Shot 2022-01-25 at 16 45 20" src="https://user-images.githubusercontent.com/685466/150952673-c41b7845-5894-49a6-8389-934ff98171e8.png">
, it's crashed:

**Comment by vyskocil** [comment] 2022-01-25 10:38
Hi @hoangbossemo !
Did you installed the compiled map on the iOS device ?

Regarding the issue when sending the app to the background I also discovered this issue recently, I'll look at this.

**Comment by vyskocil** [comment] 2022-01-25 10:50
@hoangbossemo when importing the osm data did you used a bounding polygon as in :

```~/Dev/libosmscout-vyskocil/build/Import/Import --destinationDirectory . --bounding-polygon ../greater-london.poly ../greater-london.osm.pbf  > import.log 2>&1 &```

**Comment by vyskocil** [comment] 2022-01-25 11:27
I just tried the iOS demo app with the imported database with the command line I posted previously, here are the files I copied to the document directory of the app on the iPhone :
```
-rw-r--r--    1 vyskocil  staff    725560 Jan 25 11:52 areaarea.idx
-rw-r--r--    1 vyskocil  staff    911228 Jan 25 11:52 areanode.idx
-rw-r--r--    1 vyskocil  staff     57565 Jan 25 11:52 arearoute.idx
-rw-r--r--    1 vyskocil  staff  24767092 Jan 25 11:52 areas.dat
-rw-r--r--    1 vyskocil  staff    164064 Jan 25 11:52 areasopt.dat
-rw-r--r--    1 vyskocil  staff    620989 Jan 25 11:52 areaway.idx
-rw-r--r--    1 vyskocil  staff        14 Jan 25 11:52 bounding.dat
-rw-r--r--    1 vyskocil  staff       356 Jan 25 11:52 coverage.idx
drwxr-xr-x  102 vyskocil  staff      3264 Jun 14  2020 icons
-rw-r--r--    1 vyskocil  staff    426150 Jan 25 11:52 import.log
-rw-r--r--    1 vyskocil  staff   6712208 Jan 25 11:52 intersections.dat
-rw-r--r--    1 vyskocil  staff   1972228 Jan 25 11:52 intersections.idx
-rw-r--r--    1 vyskocil  staff   5367646 Jan 25 11:52 location.idx
-rwxr-xr-x    1 vyskocil  staff     66716 Jan 25 11:52 map.ost
-rw-r--r--    1 vyskocil  staff   3403102 Jan 25 11:52 nodes.dat
-rw-r--r--    1 vyskocil  staff   1035698 Jan 25 11:52 ptroutes.dat
-rw-r--r--    1 vyskocil  staff   1318805 Jan 25 11:52 route.dat
-rw-r--r--    1 vyskocil  staff  21959761 Jan 25 11:52 router.dat
-rw-r--r--    1 vyskocil  staff       657 Jan 25 11:52 router2.dat
-rw-r--r--@   1 vyskocil  staff     50940 Jan 25 11:52 standard.oss
-rw-r--r--    1 vyskocil  staff    773328 Jan 25 11:52 textloc.dat
-rw-r--r--    1 vyskocil  staff   1199408 Jan 25 11:52 textother.dat
-rw-r--r--    1 vyskocil  staff    618784 Jan 25 11:52 textpoi.dat
-rw-r--r--    1 vyskocil  staff     13088 Jan 25 11:52 textregion.dat
-rw-r--r--    1 vyskocil  staff     36786 Jan 25 11:52 types.dat
-rw-r--r--    1 vyskocil  staff     35238 Jan 25 11:52 water.idx
-rw-r--r--    1 vyskocil  staff  13918353 Jan 25 11:52 ways.dat
-rw-r--r--    1 vyskocil  staff    432244 Jan 25 11:52 waysopt.dat
```
Then I modified the starting location in OSMScoutIOSView.m : 
```
// The center of the displayed map
#define LATITUDE 51.5102
#define LONGITUDE -0.1024
// The zoom level
#define ZOOM 16
```

Then when I launched the demo app I got : 

![Uploading IMG_A94D882EE8C7-1.jpeg…]()

**Comment by hoangbossemo** [comment] 2022-01-25 11:47
@vyskocil thanks for your help, let me try in my side

**Comment by Framstag** [comment] 2022-01-25 18:53
Since the XML import is around 10 times slower, we should also keep analyzing the protobuf problem.

The cmake configure phase should dump the version of the protobuf library. https://stackoverflow.com/questions/1085137/how-do-i-determine-the-target-architecture-of-static-library-a-on-mac-os-x gives hint regarding getting the architecture of a library.

How do you provide protobuf to the build? Do you use brew? In this case you can also query brew for the version (see https://devhints.io/homebrew).

It would still be helpful to call the Importer directly or from the debugger to see, what exactly where crashes. Based on the output above though it looks that you use a protobuf version that is part of the sdk itself.

@vyskocil Do you also use the SDK version or a different version of protobuf?

**Comment by Karry** [comment] 2022-01-25 19:31
Hi. Just for the info, I tried protobuf-based import inside aarch64 qemu on Linux and it works fine.

**Comment by hoangbossemo** [comment] 2022-01-26 02:25
@Framstag Interesting, I found the way to build success with both .osm and .pbf on my Mac. I follow this step with meson setup not cmake: https://github.com/Framstag/libosmscout/blob/master/.github/workflows/build_and%20test_on_osx.yml

btw, when I running Import, there are missing some data I marked bellow:
<img width="628" alt="Screen Shot 2022-01-26 at 09 21 40" src="https://user-images.githubusercontent.com/685466/151093429-9dc92eee-e53f-4de0-abef-6e3a7c430879.png">

This is my Import command:
<img width="578" alt="Screen Shot 2022-01-26 at 09 24 42" src="https://user-images.githubusercontent.com/685466/151093541-159c4ecf-b3b3-4571-822b-b5c3cdeace20.png">

**Comment by Framstag** [comment] 2022-01-26 05:31
cmake and meson have (partly) different approaches for finding dependencies. Than can lead to different dependencies found by cmake and meson. I thus assume that the text*.* files are missing because meson does not find the marisa dependencies. The output of the meson build configuration step should show this. The icons directory and the import.log are IMHO not part of the import. I assume that both were created by other means (e.g. manually by you?)?

Your command line still triggeres OSM XML format. For triggering the pbf backend (which is much faster in the initial import steps since it is a compressed binary format and parsing is much faster) you need to pass a *.osm.pbf file.

See for example https://download.geofabrik.de/europe/great-britain/england/greater-london.html which offers a *.osm.pbf file and a (compressed) *.osm.bz2 file.

Note that I had problems with pbf files under *windows*, too, using the vcpkg protobuf packages. I assumed that protobuf (and its usage) *might* be very strict regarding build and build options in comparison with the using application.

**Comment by vyskocil** [comment] 2022-01-26 10:29
@Framstag I still compile libosmscout with a version protobuf-2.4.1 I compiled from source  and installed a long time ago

**Comment by vyskocil** [comment] 2022-01-28 13:49
@hoangbossemo not yet but I found that the crash only occur for me when running the app connected with XCode, I didn't see it occur when the app is launched standalone on the phone.
I also did some search using Google about this error and found many hit about it, it seems it could be a uncatched C++ exception in the OSMScout lib at some deallocation but I could not spot it yet, I think I have too recompile the lib in debug...

**Comment by Framstag** [comment] 2022-07-02 18:46
@hoangbossemo: Cleaning up tickets: Is there something left to do in this ticket? Something we can or should change? Is the ticket still good for this, or should we create one or more specific tickets? Or can we even close the issue?

**Closed** 2022-09-18 17:33 UTC
Labels: bug, infrastructure, importer, build
