### ISSUE TITLE
the problem about compile error  for windows platform

### ISSUE THREAD

**Issue by lmclmc** [Framstag/libosmscout#599] opened 2018-04-19 09:28 UTC
HI, I download the libosmscout and compile osmscout2  to ubuntu platform. luckily, there is no problem.
but when I move osmscout2 to windows platform to compile, there is come trubles,
   osmscout\util\Color.cpp:31:15 :error: definition of static data member 'osmscout::Color::BLACK' of dllimport'd class

how to resolve the problem.
I will be grateful all replys.

**Comment by Framstag** [comment] 2018-04-19 17:10
@lmclmc: 

We do have centrals build using MSVC and gcc (MinGW+MSYS). Both do not fail, see https://ci.appveyor.com/project/Framstag/libosmscout

 Which build system are you using (cmake or meson)? Which compiler in which version are you using? Can you give more context regarding the build error? I assume an error in the setup, but problems in the build-script are of course also possible.

**Comment by DerKleinePunk** [comment] 2018-04-20 04:36
my fork and the build cmd with cmake and msvc 2015 and Qt5.10 also work

**Comment by lmclmc** [comment] 2018-04-20 08:12
Framstag 
the build system I am using is "Desktop QT  5.9.3 minGW 32bit", and my compiler is "minGW 5.3.0 32bit for C++",.
  **osmscout\util\Color.cpp:31:27: warning: 'osmscout::Color::BLACK' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
   const Color Color::BLACK(0.0,0.0,0.0);
 osmscout\util\Color.cpp:31:15: error: definition of static data member 'osmscout::Color::BLACK' of dllimport'd class
   const Color Color::BLACK(0.0,0.0,0.0);**

**Comment by Framstag** [comment] 2018-04-22 18:15
Hmmm, the Qt version should not be of interest. The code doe snot reference Qt at all. We do have a working build for msys 64 bit build (see for example: https://ci.appveyor.com/project/Framstag/libosmscout/build/job/stta9st2j9f6g5s3). Difference is, that you use a 32 bit build. Also our builds uses gcc 7.3.

Fro some internet search it looks like possible the DLL export/import magic is broken. Nomrally the build files in combination with the CoreExportImport header and the OSMSCOUT_API macro should handle this. So how did you build libosmscout?Do you use the cmake build or meson build or are you building the library on your own? Or you setting some manual options as part fo the build? Is there a docker image for your build environment (hmm, unlikely in the case of mingw?), where we reproduce the problem? If not, we have to give you some tips to analyse if import/export is correctly working in your build.

**Comment by lmclmc** [comment] 2018-04-23 10:25
@Framstag 
I am grateful for your aply, The cause of the problem may be my windows environment configs . I will resolve this problem by myself.

**Comment by Framstag** [comment] 2018-04-23 17:48
@lmclmc: OK, please inform us (and close the issue) if you have found the problem. If not, please send us a part of your compile log containing compiler options passed and the error itself.

**Closed** 2018-04-24 01:07 UTC
Labels: bug, build
