### ISSUE TITLE
Investigate broken coastline on basemap

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#363] opened 2017-06-07 18:14 UTC
It seems there is some problem with the basemap coastline on russia/norway.
![brokencoast](https://user-images.githubusercontent.com/6095108/26894197-f1cfccc0-4bbd-11e7-9b22-d027b569fb0d.png)

**Comment by Framstag** [comment] 2017-06-07 18:36
I have already some initial checks.

* First assumption was that coordinates are broken during parsing. For this I checked the distance between directly following point in the coastline loaded from the shape file. There were no distances greater 1.0.
* Later on we do node optimization on the coastline (CalculateCoastlineData()). This results in bigger distance, bu no distance >5.0 was found. If we skip optimization, the problem is still visible.
* Next I dropped all coastlines whose boundary.size() was <1.0. No change, problem still there (but Greece lost most of its islands).

I have to think about that... @Karry, any idea?

**Comment by Karry** [comment] 2017-06-09 06:29
Hi. I reviewed shapefile in QGis tool (thanks @rinigus for tip) and it seems that coastlines crossing 180° longitude (antimeridian) are not closed! (Same way as usual OSM coastlines...)
![unclosed-coastlines](https://user-images.githubusercontent.com/309458/26963204-c1a874e6-4ceb-11e7-8013-abb4cddacc12.png)

In OSM data, when some coastline is crossing antimeridian, it is splitted to two closed areas, like [here on Wrangel Island](http://www.openstreetmap.org/way/23824393#map=7/70.745/-179.978)

It is most likely the root of the Russia and Antarctica problems... We should try:
 - edit shapefile manually to fit this restriction
 - find another source that will preprocess shapefile same way as OSM coastlines
 - add import step that will fix this

**Comment by rinigus** [comment] 2017-06-09 07:15
I wonder if Land Polygons could be used instead (see http://openstreetmapdata.com/data/land-polygons). Or http://openstreetmapdata.com/data/water-polygons . High-resolution variants are split into smaller boxes and, I hope, they deal better with antimeridian.

**Comment by Framstag** [comment] 2017-06-09 07:22
If I understand it correctly, these are then not costlines anymore but data is more structured like WaterIndex does it in the end. This might help, if we would throw away the current water index approach completely, but else we do not get coastlines - which are required by water index - easily from this.

**Comment by Framstag** [comment] 2017-06-09 07:29
Btw., they use https://github.com/osmcode/osmcoastline/blob/master/README.md for this. As you can see, there is no option regarding anti-meridian :-/

Editing the shapefile is no option. We do want to importer newer version of the coastline to get the newest fixes.

@Karry Have you already seen where in the source coastlines crossing the anti-meridian create a problem? Perhaps there is an easy fix to be applied at some central piece of code?

Splitting the polygons is not something easy to be done. It may be simple for convex polygon but for else it is tricky. Would have to make some fancy drawing to get the algorithm...

**Comment by rinigus** [comment] 2017-06-09 07:31
Tim, yes, these are not coastlines but are usually used to draw land (or sea) directly. Let's say if we use land polygons. In Mapnik, you would draw all as sea first. Then, on top of that you draw land polygon with the land color. Then proceed as in libosmscout.

So, from what I understand how libosmscout creates water index on the basis of your explanations, it indeed does a similar job as water index. It would probably lead to simpler water index generation when using Land or Water polygons.

**Comment by Karry** [comment] 2017-06-09 07:31
Hmm, it may be little bit different. I tried updated shapefile ([Large polygons not split; 2017-05-25](http://openstreetmapdata.com/data/land-polygons)) It contains different error:
![broken-basemap-1](https://user-images.githubusercontent.com/309458/26965249-367f9db8-4cf5-11e7-89c6-a1b563b7b478.png)

I will try to run `osmcoastline` manually and try to find planet export without coastline error...

**Comment by Framstag** [comment] 2017-06-09 07:42
@rinigus: The land polygon contains edges, hat are not coastline. They just divide land into retangular areas of fitting size. This cannot be handled by libosmscout easily as import for water index.

On the other hand I'm unsure if the land polygons are good replacement for the water index (why not reuse something that others did and drop our own code?). I assume that on low zoom we will have too many polygon to draw them fast and in too high zoom situation polygon might still be too big. Water index fixes this by not just generating one data set but multiple for different resolutions. So i fear we have to write still code to handle that and are just exchanging old code we some new code.

I wold like to wait for @Karry further research before deciding how to proceed. We do not know yet what the problem is and where and our code base has a problem. To early to throw it in to the garbage ;-)

**Comment by Karry** [comment] 2017-06-09 07:49
Ah I see, my latest experiment was not with coastlines, but land polygons... (I had to update importer to accept shape type 5). I will try to find where is problem now, it is possible that there is similar problem with optimisation for low zoom like in LA...

**Comment by rinigus** [comment] 2017-06-09 07:57
Folks, I don't suggest to through out anything yet - just pointing to alternative solutions already for documentation purposes. But this has been encouraged by you as well :)

Re use of them to draw and skipping water index: What's done to make it efficient is to index (RTree or something similar) the polygons and then draw only those which are overlapping with the bounding box.

Re use with eater index: as with the drawing, if you generate water index for some bbox (not sure its done that way), you could "draw" or assign that this part is a land if its within land polygon. 

Re different zooms: for that they provide low-zoom version of the land polygons. Combining with the indexing of high-res versions, you get a decent speed of rendering.

These are just options. If it turns out to be "simple" (quoting it since its surely not simple to me) to fix, surely that's probably more efficient, at least in the short-term.

**Comment by Framstag** [comment] 2017-06-22 12:31
After the last fix of @Karry I do not have major effect anymore. Can we close the issue or are there further issues to investigate?

**Comment by Framstag** [comment] 2017-09-23 08:13
I'm closing it.

**Closed by Framstag** 2017-09-23 08:13 UTC
Labels: bug, help wanted, importer
