### ISSUE TITLE
Location index is broken for Norway

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#422] opened 2017-07-21 06:11 UTC
I have issues with location index search for Norway. After import of PBF, location search doesn't seem to cover most of the country:

```
/usr/local/osmscout/bin/LocationLookup europe-norway Oslo
Searching for pattern "Oslo"
```

When I transverse through all index using Visitors, I get rather small number of records (100K) without Oslo, for example. I haven't seen such anomaly for other countries, but Norway looks to be hit with the new location index implementation.

When testing using `LocationLookup` I coudn't get any hits with Norway, unfortunately.

**Comment by rinigus** [comment] 2017-07-21 07:40
Import log attached. Just got report from a user regarding Netherlands, seems like the same issue.

[output-no-new.txt](https://github.com/Framstag/libosmscout/files/1164768/output-no-new.txt)

**Comment by rinigus** [comment] 2017-07-21 08:23
Update: when using old version (https://github.com/rinigus/libosmscout/releases/tag/0.0.git.20170521), I get response for Oslo after Norway import using that version:

```
/usr/local/osmscout/bin/LocationLookup europe-norway "Oslo"         
Searching for pattern "Oslo"
= Oslo
   * Oslo
   - Area 176867138 boundary_state
```

**Comment by Framstag** [comment] 2017-07-21 17:49
I'll see, if I can take a look at it.

**Comment by rinigus** [comment] 2017-07-22 08:50
Sure, thank you!

**Comment by Framstag** [comment] 2017-07-22 11:57
Looks like either the index is not correctly build or is not correctly traversed. The dump of the index during import contains Oslo. But the AdminRegion visitor seems to have problems. Looks like the storage format of the root regions is unclear. Norway has multiple root regions, possibly other countries have only one and thus the problem is not visible. I have to take a further look...

**Comment by Framstag** [comment] 2017-07-22 18:27
I have now fixed the problem, but I have to increase the file format version. I would this like to make further simple changes to the location index that will break file format version, too, so that the change/fix is more worth while.

If you need the fix ASAP, I can push the fix of course earlier.

**Comment by rinigus** [comment] 2017-07-22 18:59
Thank you very much! There is no rush, I reverted to older version that worked well and would update libosmscout component later.

**Comment by Framstag** [comment] 2017-07-23 04:10
Fix pushed to github repository.

**Closed by Framstag** 2017-07-23 04:10 UTC
Labels: bug, help wanted, location

**Comment by rinigus** [comment] 2017-07-23 05:56
Thank you!
