### ISSUE TITLE
OSMScoutOpenGL crash after certain zoom on Mac.

### ISSUE THREAD

**Issue by Ycta** [Framstag/libosmscout#1095] opened 2021-05-31 20:33 UTC
Assertion failed: (neighbors_[1] != nullptr), function NeighborAcross, file /Projects/libosmscout-code/libosmscout-map-opengl/src/poly2tri/common/shapes.cc, line 350.

Any idea how to fix this?

**Comment by Framstag** [comment] 2021-06-03 18:20
Hello Ycta. The OpenGL backend is currently not maintained. It is also not in similar quality as the other rendering backends. The Poly2Tri sources also were not developed by the libosmscout maintainers (see copyright header of these files).

Looking at the usage fo the function NeighborAcross(), it looks like it is not directly called by libosmscout code but by other parts of the Poly2Tri code. 

It is possible that the data passed to the Poly2Tri code does not fulfil implicit requirements of the library. It would be helpful to isolate the actual data set (and its value) that breaks the renderer to see if it is not valid (like for example an illegal geometric form). This way we can add a filter step to the importer or during render time to drop such broken data.

**Comment by Ycta** [comment] 2021-06-06 20:57
Example "works" on Windows 10. But I noticed that nothing is being drawn. It's because there are no shaders anywhere.

Can you please provide me with the shader program files, like "AreaVertexShader.vert" etc. Referenced in the OSMScoutOpenGL

**Comment by Ycta** [comment] 2021-06-06 21:40
Okay I've fixed the issue, it was not drawing anything because shaders are in different folder.
Changed
`      std::ifstream myfile(dirPath + "osmscout/private/" + name);`
at line 100 in OpenGLMapData.h 
to
` std::ifstream myfile(dirPath + "/osmscout/private/" + name);`

[That fixed it.](https://i.gyazo.com/8c5659fb02a4835eea0fab7a021c6eb3.png)

**Comment by Ycta** [comment] 2021-06-06 22:18
[Now text rendering is messed up, guess it's character encoding?](https://i.gyazo.com/5b66cb4181d416887db1cfbc204b7685.png)

**Comment by Framstag** [comment] 2021-06-08 04:29
Depending on the OS this is a known issue: See https://github.com/Framstag/libosmscout/issues/469

**Comment by Karry** [comment] 2021-12-09 23:05
Problem with hardcoded path to shaders is addressed in this merge request: https://github.com/Framstag/libosmscout/pull/1167

The crash may be caused by out-of-bounds memory access. When demo is compiled with memory sanitizer, it is obvious where it is (on Linux, GCC). I will try to fix this in future merge request(s).

**Comment by Karry** [comment] 2021-12-17 17:33
Hi @Ycta , may I close this issue? OpenGL demo fails gracefully now, when shaders are not found in install path. It should not crash anymore. I also solved some memory access issues, that could have cause crashe...

Text rendering still has some issues on OpenGL (it leaks memory, last character is missing on Linux...). But we have separate issue for it.

**Closed** 2021-12-29 09:51 UTC
Labels: bug, help wanted, renderer, OpenGL
